Add: センサデータを取得するコンポーネントを追加
Toya-Onodera/WebBrowserMotionDataCollector pull request #16
Opened 2022-04-23 19:07 UTC by ok-tomo

### 関連する Issue

close #9 

### やったこと

- `deviceorientation`イベント、`devicemotion`イベントからセンサデータを取得
- 取得したデータをsetStateを用いてstateへ格納

### やらないこと

- UI部分への反映

### できるようになること（ユーザ目線）

- なし

### できなくなること（ユーザ目線）

- なし

### 動作のスクリーンショット

- なし

### その他

カスタムフックが未実装なのですが、ロジック部分や書き方が大丈夫であるか確認お願いしたいです。

2022-04-24 06:10 UTC, ok-tomo commented
@Toya-Onodera 
よろしくお願いします:bow:

2022-04-25 02:42 UTC, Toya-Onodera requested changes
とりあえず少し細かめにチェックしました！
あとは iOS で動作しないコードになっているのでこの部分の実装が済んだら追加したいって感じです 👀 
ひとまず修正よろしくお願いします！

2022-04-25 02:42 UTC, Toya-Onodera commented on src/components/organisms/MobileSensorData/MobileSensorData.tsx
> +    useState<DeviceMotionEventRotationRate | null>(null);
ここの型定義、可読性上げるために新しく作りますか

2022-04-25 02:42 UTC, Toya-Onodera commented on src/components/organisms/MobileSensorData/MobileSensorData.tsx
> +    useState<DeviceMotionEventRotationRate | null>(null);
```javascript
type Orientation = DeviceOrientationEvent | null;
type Acceleration = DeviceMotionEventAcceleration | null;
type AccelerationIncludeGravity = DeviceMotionEventAcceleration | null;
type RotationRate = DeviceMotionEventRotationRate | null;

const [deviceOrientation, setDeviceOrientation] = useState<Orientation>(null);
const [acceleration, setAcceleration] = useState<Acceleration>(null);
const [accelerationIncludeGravity, setAccelerationIncludeGravity] = useState<AccelerationIncludeGravity>(null);
const [rotationRate, setRotationRate] = useState<RotationRate>(null);
```

が良さそう

2022-04-25 02:42 UTC, Toya-Onodera commented on src/components/organisms/MobileSensorData/MobileSensorData.tsx
> +  }, []);
引数名はわかりやすいほうが良いので（型がわかるからそんな気にしなくても良い気がするけど）

```javascript
useEffect(() => {
  const orientationHandler = (orientation: DeviceOrientationEvent) => {
    setOrientation(orientation);
  };

  const motionHandler = (event: DeviceMotionEvent) => {
    const { acceleration, accelerationIncludingGravity, rotationRate } =
      event;
 
    setAcceleration(acceleration);
    setAccelerationIncludeGravity(accelerationIncludingGravity);
    setRotationRate(rotationRate);
 };

  window.addEventListener("devicemotion", motionHandler);
  window.addEventListener("deviceorientation", orientationHandler);
}, []);
```

がいいかも

2022-04-25 02:42 UTC, Toya-Onodera commented on src/components/organisms/MobileSensorData/MobileSensorData.tsx
> +  }, []);
```javascript
const { acceleration, accelerationIncludingGravity, rotationRate } =
      event;
```

ここは、分割代入を使うとすっきり書けます。（好み）

```javascript
const motionHandler = ({
  acceleration,
  accelerationIncludingGravity,
  rotationRate,
}: DeviceMotionEvent) => {
  setAcceleration(acceleration);
  setAccelerationIncludeGravity(accelerationIncludingGravity);
  setRotationRate(rotationRate);
};
```

と書くこともできます

2022-04-25 02:42 UTC, Toya-Onodera commented on src/components/pages/IndexPage/IndexPage.tsx
> +          rotationRateLists={rotationRateLists}
ここの Props は消しちゃいますか

2022-04-25 02:42 UTC, Toya-Onodera commented on src/components/pages/IndexPage/IndexPage.tsx
> +          rotationRateLists={rotationRateLists}
せっかくなので表示の部分指摘しますね
```javascript
const deviceUseLists = useMemo(() => {
  return [
    "ブラウザ名: platform.name",
    "ブラウザバージョン: platform.version",
    "端末名: platform.product",
    "端末OS名: platform.os.family",
  ];
}, []);

const deviceorientationLists = useMemo(() => {
  if (orientation) {
    const { alpha, beta, gamma } = orientation;
    return [`x軸: ${alpha}`, `y軸: ${beta}`, `z軸: ${gamma}`];
  }

  return [
    "x軸: deviceorientation.alpha",
    "y軸: deviceorientation.beta",
    "z軸: deviceorientation.gamma",
  ];
}, [orientation]);

const accelerationLists = useMemo(() => {
  if (acceleration) {
    const { x, y, z } = acceleration;
    return [
      `x軸(西から東へ向かう軸): ${x}`,
      `y軸(南から北へ向かう軸): ${y}`,
      `z軸(地面から直立する軸): ${z}`,
    ];
  }

  return [
    "x軸(西から東へ向かう軸): acceleration.x",
    "y軸(南から北へ向かう軸): acceleration.y",
    "z軸(地面から直立する軸): acceleration.z",
  ];
}, [acceleration]);

const accelerationIncludingGravityLists = useMemo(() => {
  if (accelerationIncludingGravity) {
    const { x, y, z } = accelerationIncludingGravity;
    return [`x軸: ${x}`, `y軸: ${y}`, `z軸: ${z}`];
  }

  return [
    "x軸: accelerationIncludingGravity.x",
    "y軸: accelerationIncludingGravity.y",
    "z軸: accelerationIncludingGravity.z",
  ];
}, [accelerationIncludingGravity]);

const rotationRateLists = useMemo(() => {
  if (rotationRate) {
    const { alpha, beta, gamma } = rotationRate;
    return [
      `alpha軸(西から東へ向かう軸): ${alpha}`,
      `beta軸(南から北へ向かう軸): ${beta}`,
      `gamma軸(地面から直立する軸): ${gamma}`,
    ];
  }

  return [
    "alpha軸(西から東へ向かう軸): rotationRate.x",
    "beta軸(南から北へ向かう軸): rotationRate.y",
    "gamma軸(地面から直立する軸): rotationRate.z",
  ];
}, [rotationRate]);
```

みたいにデータを作成してコンポーネントにデータを入れるように書くと良いかと思います

2022-04-25 02:42 UTC, Toya-Onodera commented on src/components/organisms/MobileSensorData/MobileSensorData.tsx
> +  const [accelerationIncludeGravity, setAccelerationIncludeGravity] =
ここ、typo しているので `const [accelerationIncludingGravity, setAccelerationIncludingGravity] =
      useState<AccelerationIncludeGravity>(null);` に直しますか

2022-04-25 02:43 UTC, Toya-Onodera commented
うまく修正すると Android では動作するようになると思う（iOS しか持っていない場合はコードレビューで動作見ます）

2022-04-26 06:22 UTC, Toya-Onodera requested changes
@ok-tomo 
直さなくても iOS でも動く感じだったんだけど
バグ出たときに修正が大変そうな感じになりそうなので、MUI を使ってダイアログを表示する動作に変更しました！

https://user-images.githubusercontent.com/11432913/165234853-7c6e6988-5b08-4449-bc6e-6a9be2ddb29a.MP4

次は、カスタム Hooks にまとめる作業をお願いします 👀 
よろしくお願いします

2022-04-26 06:22 UTC, Toya-Onodera commented on src/components/organisms/MobileSensorData/MobileSensorData.tsx
> +  }, [rotationRate]);
ここの部分を `src/components/organisms/MobileSensorData/MobileSensorData.hooks.tsx` にまとめてみましょうか

2022-04-26 06:22 UTC, Toya-Onodera commented on src/components/organisms/MobileSensorData/MobileSensorData.tsx
> +  }, [rotationRate]);
`useMobileSensorData` として定義して（カスタム Hooks は useXxx で命名しなくてはいけない）

- deviceUseLists
- deviceorientationLists
- accelerationLists
- accelerationIncludingGravityLists
- rotationRateLists

を return する感じでコードを書けば良さそう

2022-04-26 06:22 UTC, Toya-Onodera commented on src/components/organisms/MobileSensorData/MobileSensorData.tsx
> +  }, [rotationRate]);
```javascript
const { 
    deviceUseLists
    deviceorientationLists
    accelerationLists
    accelerationIncludingGravityLists
    rotationRateLists
} = useMobileSensorData();
```

って感じでデータを持ってくればいい感じに動くと思います

2022-05-06 10:24 UTC, Toya-Onodera approved these changes
![https://www.lgtm.app/p/Ktak1_6LC](https://www.lgtm.app/p/Ktak1_6LC)

2022-05-06 10:25 UTC, Toya-Onodera commented
@ok-tomo 
あとはマージお願いします！

2022-05-06 15:57 UTC, ok-tomo commented
ありがとうございます:bow:

2022-05-06 15:57 UTC, merged