端末情報を表示・Firebaseへ格納する処理を実装
Toya-Onodera/WebBrowserMotionDataCollector pull request #21
Opened 2022-05-27 17:00 UTC by ok-tomo

### 関連する Issue

close #20

### やったこと

- `userAgent`から端末情報を取得し、画面上に表示する
- 取得した端末情報をFirebaseへ格納する
- Firebaseへ格納する処理に合わせ、データ構造を`sensorData`と`platform`の2つに変更

### やらないこと

- 保存したデータのDL機能の実装

### できるようになること（ユーザ目線）

- 端末情報が画面上に表示される

### できなくなること（ユーザ目線）

- なし

### 動作のスクリーンショット

- Chrome
<img src="https://user-images.githubusercontent.com/79753068/170742983-92fc5efa-3b40-4555-9286-c5ccb0e4c526.PNG" width="360">

- Firefox
<img src="https://user-images.githubusercontent.com/79753068/170742988-bc0ab90b-8aa9-4b79-acde-2a0fab258947.PNG" width="360">

- Safari
<img src="https://user-images.githubusercontent.com/79753068/170742993-baccb96e-7caa-4d8f-95c4-154e8ca017be.PNG" width="360">

### その他

少し付けたしただけですが、確認よろしくお願いします:bow:

2022-05-28 02:04 UTC, Toya-Onodera requested changes
ここだけ修正お願いします！

2022-05-28 02:04 UTC, Toya-Onodera commented on src/components/organisms/MotionSensorFloatingButton/MotionSensorFloatingButton.hooks.tsx
> +  const platform = mobileContext.platform;
ここだけ念の為に、`useMemo` 使っときましょうか 👀

2022-05-28 10:04 UTC, ok-tomo commented
@Toya-Onodera 
修正終わりました！
確認よろしくお願いします:bow:

2022-05-30 02:24 UTC, Toya-Onodera approved these changes
![https://www.lgtm.app/p/4PSFquCql](https://www.lgtm.app/p/4PSFquCql)
良さそうです 👀 
マージお願いします 🙇

2022-05-30 03:39 UTC, ok-tomo commented
ありがとうございます！

2022-05-30 03:39 UTC, merged